spring.application.name=PlayStore
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/PlayStore
spring.datasource.username=postgres
spring.datasource.password=Ramesh@123
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.root=INFO